server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password:
    driverClassName: org.h2.Driver
    ddl-auto: create-drop
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console.enabled: true

